name = "ygom-site"
compatibility_date = "2025-07-09"

routes = [
  { pattern = "ygom.top", custom_domain = true },
  { pattern = "www.ygom.top", custom_domain = true }
]

[assets]
directory = "./site"
not_found_handling = "single-page-application"

[vars]
