name: 'Purge release cache'

run-name: ${{ inputs.reason }}

on: 
  push:
    branches:
      - 'main'
    paths:
      - 'ver_code.txt'
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running this action, can be omitted'
        required: false
        type: string
        default: 'Purge release cache, manually triggered'

jobs:
  cloudflare-purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudflare Purge Cache
        uses: fishmanlabs/cloudflare-purge-cache-action@v1
        with:
          zone_id: ${{secrets.CLOUDFLARE_ZONEID}}
          api_token: ${{secrets.CLOUDFLARE_API_TOKEN}}
          purge_everything: false
          purge_files: |
            https://ygom.top
            https://ygom.top/bdunion.txt
            https://ygom.top/ver_code.txt
            https://static.ygom.top/files/YGOMobile_latest.Apk

          
